### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by zc994646659** [jichunlian/disorder#2]
连老师你好，我想用disorder给我的结构体系MnN产生一些N空位模拟，一些输入参数，命令的使用，都不太清楚，能不能像您请教下。

**Comment by jichunlian** [comment]
好的，非常欢迎，能不能具体描述一下你的问题呢

**Comment by zc994646659** [comment]
老师，我发你湖南大学邮箱了 ，您可能没收到，就是怎么使用disorder程序 产生一些原子替换，空位替换的结构，我看了输入参数 INDSOD，不是很了解每个参数的意思。其实我也好奇如果我直接增删原子是不是也能达到同样的效果，那disorder的作用在于随机性吗，也看了一些算法，也希望老师给予一些指导，感谢，我是吉林大学博一的学生，我叫周超。
